### ISSUE TITLE
Done

### ISSUE THREAD

**Issue by akatama-ai** [OnGridSystems/coinpayments-py#1]

**Comment by akatama-ai** [comment]
hi

**Comment by ongrid** [comment]
Hi @loctai. It looks these method were added recently. @profx5 could you please take a look and add them?

**Comment by akatama-ai** [comment]
i need your help @ongrid  @profx5

**Comment by rnesytov** [comment]
Done https://github.com/OnGridSystems/coinpayments-py/commit/04df7f2e763bf72e85a8db7853cb656dbb4b65fe

**Comment by akatama-ai** [comment]
I used the create_mass_withdrawal function but it didn't work. help me.

data = {
    "wd": {
      "wd1": {
        "address": "0xaa8575f8049b684e82076f757430f31139fc4b5d", 
        "amount": 1.6, 
        "currency": "ETH"
      }, 
      "wd2": {
        "address": "0xac338d9faac562df26d702880c796e1024e2698a", 
        "amount": 0.4, 
        "currency": "ETH"
      }
    }
 }

ClientCoinpayment.create_mass_withdrawal(wd = data) 
Result: {'error': "No 'wd' array passed!", 'result': []}
